# ---------- 1. deps ----------
FROM oven/bun:latest AS deps
WORKDIR /frontend
COPY package.json bun.lock* ./
RUN bun install --frozen-lockfile

# ---------- 2. build ----------
FROM oven/bun:latest AS build
WORKDIR /frontend
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=deps /frontend/node_modules ./node_modules
COPY . .
RUN bun run build

# ---------- 3. runner ----------
FROM node:latest AS runner
WORKDIR /frontend

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    # HOSTNAME="0.0.0.0" \
    PORT=3000

COPY --from=build /frontend/.next/standalone ./
COPY --from=build /frontend/.next/static ./.next/static
COPY --from=build /frontend/public ./public

EXPOSE 3000
CMD ["node", "server.js"]
    