# ====== СБОРОЧНЫЙ ЭТАП ====== 
FROM oven/bun:latest

# Установка OpenSSL
RUN apt-get update \
 && apt-get install -y openssl \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Установка зависимостей с кэшированием
COPY package.json bun.lock ./
RUN bun install

# Копирование исходного кода
COPY . .

# Настройка для отладки
ENV NODE_ENV=development
ENV BUN_ENV=development

EXPOSE $BACKEND_PORT 9229
CMD ["bun", "run", "start:dev"]